    self.device.shutdown(socket.SHUT_RDWR)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function Escpos.__del__ at 0x7f8df0bb45e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/escpos/escpos.py", line 69, in __del__
    self.close()
  File "/usr/local/lib/python3.8/dist-packages/escpos/printer.py", line 245, in close
    self.device.shutdown(socket.SHUT_RDWR)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function Escpos.__del__ at 0x7f8df0bb45e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/escpos/escpos.py", line 69, in __del__
    self.close()
  File "/usr/local/lib/python3.8/dist-packages/escpos/printer.py", line 245, in close
    self.device.shutdown(socket.SHUT_RDWR)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function Escpos.__del__ at 0x7f8df0bb45e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/escpos/escpos.py", line 69, in __del__
    self.close()
  File "/usr/local/lib/python3.8/dist-packages/escpos/printer.py", line 245, in close
    self.device.shutdown(socket.SHUT_RDWR)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function Escpos.__del__ at 0x7f8df0bb45e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/escpos/escpos.py", line 69, in __del__
    self.close()
  File "/usr/local/lib/python3.8/dist-packages/escpos/printer.py", line 245, in close
    self.device.shutdown(socket.SHUT_RDWR)
OSError: [Errno 9] Bad file descriptor
The media.width.pixel field of the printer profile is not set. The center flag will have no effect.
The media.width.pixel field of the printer profile is not set. The center flag will have no effect.
